title: David Thomas - CV
description: David Thomas' CV
baseurl: "https://theportus.github.io/"

username: David Thomas
typing_text: Digital Scholar, Ancient Historian

email: dave.a.base@gmail.com
github_username: theportus

show_aboutme_card: true
about_me_title: About Me
about_me_description: I am David Thomas, a Digital Scholar and Ancient Historian. I teach, advise, and code Digital Scholarship projects including full stack web apps. In addition to teaching at the university level, I have also worked professionally as a public school teacher and as an instructor for an intensive summer camp for gifted children. I have worked with students from middle school through college, and with varied skills, backgrounds, and challenges. As the son of two educators, teaching, whatever the subject, has been my lifelong calling. Above all, I strive to make scholars and students as critical about data as they are about texts.

show_skills_card: true
skills_title: Skills

show_timeline_card: true
timeline_education_title: Education
timeline_work_title: College Teaching Experience
cv_download_link: https://theport.us/wp-content/uploads/2022/06/CV.pdf

show_projects_card: true
show_projects: true
projects_title: Select Projects
show_os_projects: false
os_projects_title: Portfolio Projects

show_contact_card: true
contact_title: Contacts
contact_description: Contact me

repository: theportus/theportus.github.io
github_pages:
  - networks-of-roman-eleusis
  - asc-analysis
  - dhelp
  - theportus.github.io
  
projects:
  sort_by: stars
  exclude:
    archived: true
    forks: true
    projects:
      - theportus

plugins:
  - "jekyll-github-metadata"

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json",
  ]
